name: ascii-image-converter
base: core18 
version: "1.13.1"
summary: Convert images and gifs into ascii art
description: |
  ascii-image-converter is a command-line tool that converts images into ascii art and prints
  them out onto the console. Supported input formats are JPEG/JPG, PNG, WEBP, BMP, TIFF/TIF and GIF.
  Now supports braille art.

grade: stable
confinement: strict

license: Apache-2.0
    
parts:
  ascii-image-converter:
    plugin: go
    go-importpath: github.com/TheZoraiz/ascii-image-converter
    source: .
    build-packages:
      - gcc

apps:
  ascii-image-converter:
    command: bin/ascii-image-converter
    plugs:
    - home
    - network
    
architectures:
  - build-on: amd64
    run-on: [amd64, i386, arm64, armhf, s390x, ppc64el]
